# Hooks
require_dependency 'redmine_rate/hooks/project_hook'
require_dependency 'redmine_rate/hooks/memberships_hook'
require_dependency 'redmine_rate/hooks/timesheet_hook_helper'
require_dependency 'redmine_rate/hooks/plugin_timesheet_views_timesheets_time_entry_row_class_hook'
require_dependency 'redmine_rate/hooks/plugin_timesheet_views_timesheet_group_header_hook'
require_dependency 'redmine_rate/hooks/plugin_timesheet_views_timesheet_time_entry_hook'
require_dependency 'redmine_rate/hooks/plugin_timesheet_views_timesheet_time_entry_sum_hook'
require_dependency 'redmine_rate/hooks/plugin_timesheet_view_timesheets_report_header_tags_hook'
require_dependency 'redmine_rate/hooks/view_layouts_base_html_head_hook'

